services:
  robot-api:
    image: robot-api:1.0.0
    container_name: robot-api-staging
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_HTTP_PORTS: 8080
    restart: unless-stopped
